// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waordtqaedotvkegiuhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhb3JkdHFhZWRvdHZrZWdpdWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTMwMjMsImV4cCI6MjA1OTQ4OTAyM30.jnUEwR80vnbm9fmUK487vJfXjFC5jzfVXnhE67_eIHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);